name: Lint

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "apps/**"
      - "packages/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          enable-cache: true
      - run: uv run bash scripts/lint.sh
